services:
  app:
    image: node:16
    command: sh -c "npm install && npm start"
    ports:
     - 3000:3000
    working_dir: /project-atelier-products-backend
    volumes:
     - ./:/project-atelier-products-backend